import type { Metadata } from "next";
import "./globals.css";
import { Navbar01 } from "@/components/nav/navbar";
import { ThemeProvider } from "@/components/theme/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased bg-white"
      >
         <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
       <div className=" w-full flex items-center justify-center mt-5">
          <Navbar01/>
       </div>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
